catcollector_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('api/', views.api, name='api'),
    path('cats/', views.cats_index, name='cats_index'),
    path('cats/<int:cat_id>/', views.cats_detail, name='detail'),
    path('cats/<int:cat_id>/delete/', views.cats_delete, name='cats_delete'),
    path('cats/<int:cat_id>/edit/', views.cats_edit, name='cats_edit'),
    path('cats/<int:cat_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    path('cats/<int:cat_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
    path('cats/<int:cat_id>/deassoc_toy/<int:toy_id>/', views.deassoc_toy, name='deassoc_toy'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner'),
)

# Create your models here.

class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Cat(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    # more black magic from django
    toys = models.ManyToManyField(Toy) # creates a join table and then you will be able to acceess the join table 
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

# this is an example of a join table that django creates for us
# class Cat_Toys(models.Model):
#     cat_id = models.ForeignKey(Cat, on_delete=models.CASCADE)
#     toy_id = models.ForeignKey(Toy, on_delete=models.CASCADE)


class Feeding(models.Model):
    date = models.DateField('feeding date')
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
    )
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE, default=0)

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']


# Ways to create/query/edit/delete data:
# 1. Through the app (forms, links, etc)
# 2. Through the Django/Python shell (python3 manage.py shell)
# 3. Through the psql shell
# 4. Through the admin panel at /admin

main_app/forms.py
from django.forms import ModelForm
from .models import Cat, Feeding


class Cat_Form(ModelForm):
    class Meta:
        model = Cat
        fields = ['name', 'breed', 'description', 'age']

class Feeding_Form(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal', 'cat']
        

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .models import Cat, Toy
from .forms import Cat_Form, Feeding_Form
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

# Create your views here.

# --- Base Views ---
def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


def api(request):
    return JsonResponse({"status": 200})

# --- Cat Views ---

# index and create
@login_required
def cats_index(request):
    if request.method == 'POST':
        cat_form = Cat_Form(request.POST)
        if cat_form.is_valid():
            # save(commit=False) will just make a copy/instance of the model
            new_cat = cat_form.save(commit=False)
            new_cat.user = request.user
            # save() to the db
            new_cat.save()
            return redirect('cats_index')
    cats = Cat.objects.filter(user=request.user)
    cat_form = Cat_Form()
    context = {'cats': cats, 'cat_form': cat_form}
    return render(request, 'cats/index.html', context)

# show
@login_required
def cats_detail(request, cat_id):
    cat = Cat.objects.get(id=cat_id)
    # [3,1] is what is returned cat.toys.all().values_list('id')
    toys_cat_doesnt_have = Toy.objects.exclude(id__in=cat.toys.all().values_list('id')) # get all toys where the cat id is not associated in the jion table
    feeding_form = Feeding_Form()
    context = {'cat': cat, 'feeding_form': feeding_form, 'available_toys': toys_cat_doesnt_have}
    return render(request, 'cats/detail.html', context)

# edit && update
@login_required
def cats_edit(request, cat_id):
  cat = Cat.objects.get(id=cat_id)
  # The following line is untested, but the idea is
  # that we only want cat owners to be able to
  # edit cats (or delete in the cats_delete view)
  # In order to do this, you can include logic here
  # that compares the cat's user to the logged-in
  # user. Everything below it would then need to become
  # part of that if-check and then an additional
  # response would need to be set up to let the user they
  # aren't allowed to perform that action.
  # if cat.user == request.user:
  if request.method == 'POST':
    cat_form = Cat_Form(request.POST, instance=cat)
    if cat_form.is_valid():
      cat_form.save()
      return redirect('detail', cat_id=cat_id)
  else:  
    # in form(instance=The object that we pull back from db)
    cat_form = Cat_Form(instance=cat)
  context = {'cat': cat, 'cat_form': cat_form}
  return render(request, 'cats/edit.html', context)

# delete
@login_required
def cats_delete(request, cat_id):
    Cat.objects.get(id=cat_id).delete()
    return redirect("cats_index")

# --- Feeding Views ---

@login_required
def add_feeding(request, cat_id):
  import copy
  full_request = copy.copy(request.POST)
  full_request['cat'] = cat_id
  feeding_form = Feeding_Form(full_request)
  if feeding_form.is_valid():
    feeding_form.save()
  return redirect('detail', cat_id=cat_id)

  # print('NOW PRINTING request.post')
  # print(request.POST)
  # full_request = {}
  # full_request['date'] = request.POST['date']
  # full_request['meal'] = request.POST['meal']

  # full_request.cat_id = cat_id
  # print('NOW PRINTING full_request')
  # print(full_request)

  # print('NOW PRINTING feeding form')
  # print(feeding_form)

    # new_feeding = feeding_form.save(commit=False)
    # print('NOW PRINTING new feeding')
    # print(new_feeding)

    # new_feeding.cat_id = cat_id
    # new_feeding.save()

    # feeding_form.save(commit=False)
    # feeding_form.cat_id = cat_id


# --- Toy Views ---

@login_required
def assoc_toy(request, cat_id, toy_id):
    Cat.objects.get(id=cat_id).toys.add(toy_id)
    # Cat.objects.get(id=cat_id) return Cat(1) Eldritch
    # Cat.toys returns the join table 
    # table.add -> creates an row in the join table the id provided
    # cat 1 | toy 3 
    return redirect('detail', cat_id=cat_id)

@login_required
def deassoc_toy(request, cat_id, toy_id):
    Cat.objects.get(id=cat_id).toys.remove(toy_id)
    return redirect('detail', cat_id=cat_id)

# --- Signup View ---

def signup(request):
    error_message = ''
    if request.method == 'POST':
      form = UserCreationForm(request.POST)
      if form.is_valid():
        user = form.save()
        login(request, user)
        return redirect('cats_index')
      else:
        error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
  <h1>About the Cat Collector</h1>
  <hr />
  <p>Hire the Cat Collector!</p>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Cat Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'styles/main.css' %}" >
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;CatCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'cats_index' %}">{{ user.username }}'s Cats</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2019 Cat Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/cats/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Cat Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ cat.name }}</span>
                <p>Breed: {{ cat.breed }}</p>
                <p>Description: {{ cat.description }}</p>
                {% if cat.age > 0 %}
                <p>Age: {{ cat.age }}</p>
                {% else %}
                <p>Age: Kitten</p>
                {% endif %}
            </div>
            <!-- card actions -->
            <div class="card-action">
                <a href="{% url 'cats_edit' cat.id %}" class="btn blue">Edit</a>
                <a class="btn red" href="{% url 'cats_delete' cat.id %}">Delete</a>
            </div>
        </div>
    </div>
    <div class="col s6">
        <form action="{% url 'add_feeding' cat.id %}" method="POST">
            {% csrf_token %}
            {{ feeding_form.as_p }}
            <input type="submit" class="btn" value="Add Feeding">
        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Meal</th>
                </tr>
            </thead>
            <tbody>
                {% for feeding in cat.feeding_set.all %}
                    <tr>
                        <td>{{feeding.date}}</td>
                        <td>{{feeding.get_meal_display}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<!-- toys -->
<hr>
<div class="row">
    <!-- toys owned by cat -->
    <div class="col s6" >
        <h3>{{cat.name}}'s Toys</h3>
        {% if cat.toys.count %}
            
            {%for toy in cat.toys.all %}
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">
                        A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
                        </span>
                    </div>
                    <div class="card-action">
                        <form action="{% url "deassoc_toy" cat.id toy.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn red">Remove</button>
                        </form>
                    </div>
                </div>
            {% endfor %}

        {% else %}
            <h5>No toys :(</h5>
        {% endif %}
    </div>
    <!-- Toys available to cat -->
    <div class="col s6" >
        <h3>Available toys</h3>
        
        {% if available_toys.count %}
            {%for toy in available_toys %}
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">
                        A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
                        </span>
                    </div>
                    <div class="card-action">
                        <form action="{% url "assoc_toy" cat.id toy.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn">Add</button>
                        </form>
                    </div>

                </div>
            {% endfor %}
        {% else %}
            has all toys
        {% endif %}

    </div>
</div>


<!-- bottom of toys -->
<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true,
    })

    const selectEl = document.getElementById('id_meal');
    M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/cats/edit.html
{% extends 'base.html' %}


{% block content %}

<h1>Edit {{ cat.name }}</h1>

<form action="{% url 'cats_edit' cat.id %}" method="POST">
  {% csrf_token %}
  {{ cat_form.as_p }}
  <input class="btn" type="submit" value="Update {{cat.name}}">
</form>

{% endblock %}

main_app/templates/cats/index.html
{% extends 'base.html' %} {% block content %}

<div class="row">
  <h1>{{ user.username }}'s Cat List</h1>

  <div class="col s9">
    {% for cat in cats %}
    <div class="card">
      <a href="{% url 'detail' cat.id %}">
        <div class="card-content">
          <span class="card-title">{{ cat.name }}</span>
          <p>Breed: {{ cat.breed }}</p>
          <p>Description: {{ cat.description }}</p>
          {% if cat.age > 0 %}
          <p>Age: {{ cat.age }}</p>
          {% else %}
          <p>Age: Kitten</p>
          {% endif %}
        </div>
      </a>
    </div>
    {% endfor %}
  </div>

  <div class="col s3">
    <form action="{% url 'cats_index' %}" method="POST">
      {% csrf_token %} {{ cat_form.as_p }}
      <input type="submit" class="btn" value="Add cat" />
    </form>
  </div>
</div>

{% endblock %}

main_app/templates/costumes/index.html
{% extends 'base.html' %} {% block content %}
<h1>Costumes!</h1>
<div class="row">
  <div class="col s12">
    {% for costume in costumes %}

    <div class="card">
      <div class="card-image">
        <img src="{{costume.image}}" />
        <span class="card-title">{{costume.name}}</span>
      </div>
      <div class="card-content">
        <h4>Owned by: {{costume.cat.name}}</h4>
      </div>
    </div>

    {% endfor %}
  </div>
</div>
{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}

<h1>Hello /ᐠ｡‸｡ᐟ\ﾉ</h1>

{% endblock %}